# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"^\n\x0bPlayerState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x08position\x18\x02 \x01(\x0b\x32\x05.Vec3\x12\x17\n\x08rotation\x18\x03 \x01(\x0b\x32\x05.Vec3\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"@\n\nWorldState\x12\x1d\n\x07players\x18\x01 \x03(\x0b\x32\x0c.PlayerState\x12\x13\n\x0bserver_time\x18\x02 \x01(\x03\"2\n\x0b\x42otMoveData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x08position\x18\x02 \x01(\x0b\x32\x05.Vec3\"*\n\x0c\x42otMoveBatch\x12\x1a\n\x04\x62ots\x18\x01 \x03(\x0b\x32\x0c.BotMoveDataB\x1a\xaa\x02\x17Synapse.Shared.Protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027Synapse.Shared.Protocol'
  _globals['_VEC3']._serialized_start=14
  _globals['_VEC3']._serialized_end=53
  _globals['_PLAYERSTATE']._serialized_start=55
  _globals['_PLAYERSTATE']._serialized_end=149
  _globals['_WORLDSTATE']._serialized_start=151
  _globals['_WORLDSTATE']._serialized_end=215
  _globals['_BOTMOVEDATA']._serialized_start=217
  _globals['_BOTMOVEDATA']._serialized_end=267
  _globals['_BOTMOVEBATCH']._serialized_start=269
  _globals['_BOTMOVEBATCH']._serialized_end=311
# @@protoc_insertion_point(module_scope)
